### PR TITLE
Implementation of result line

### PR DESCRIPTION
**Pull request by mscno**
I added an initial implementation for showing result line (income + expenses).

This allows to quickly see the operation result for any given period, and to understand the amount that is transferred to equity for the next period.

### CODE REVIEW

**Comment by sboehler** [comment]
You can get the same effect more generally using some available switches

Option 1) Using the `-r` flag:

```
knut balance finance.knut --last 12 --months -r Expenses -m1 -vUSD
```

Not sure it is documented properly, but it takes a regex and will remap the first segment of the account name it as follows:

Income is mapped to Expenses
Expenses is mapped to Income

Assets is mapped to Liabilities
Liabilities is mapped to Assets

This is useful because technically there is no difference between an Income and an Expense account, besides aeathetics.

Option 2) Using the `-m0` switch with a regex. For example:

```
knut balance finance.knut --last 12 --months -m0,"^(Expenses|Income)" -m2 -vCHF
```

which prints the difference ("all the accounts mapped to 0 levels") in the "Delta" line at the bottom.

These two options allow for more flexibility than this PR, as they allow for targetting individual accounts. For example, I might be interested in the net income defined as work (but not investment) income, minus taxes and costs of living (but not investment expenses).

**Comment by mscno** [comment]
Thanks for the prompt reply!

The -r flag solves exactly what I was looking for. Just didnt find it in the readme, so thats why i cooked together this PR instead.

Will close this PR, as the `-r` flag solves the issue of creating a result line.

**Comment by mscno** [comment]
Was also able to achieve the same with `knut balance --years "-m0,(Equity|Assets|Liabilities)" finance.knut -vUSD`, as this also generates an income statement with the result line being in the total row.

Great library you have put together!

**Comment by sboehler** [comment]
Thank you :-)

I continued to play arond with your idea a bit. While I think the net income would be useful to have, the problem is that I don't find a visually pleasing way to add subtotals to the `balance` report. 

With subtotals on the EIE side of the balance, everything becomes less symmetric. Plus, subtotals make it harder to see that "knut always balances" (a core principle), as they add visual clutter no matter what.

**Pull request closed without merging**
